# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "web3", to: "https://ga.jspm.io/npm:web3@4.2.0/lib/esm/index.js"
pin "@adraffy/ens-normalize", to: "https://ga.jspm.io/npm:@adraffy/ens-normalize@1.10.0/dist/index.mjs"
pin "@ethereumjs/rlp", to: "https://ga.jspm.io/npm:@ethereumjs/rlp@4.0.1/dist/index.js"
pin "@noble/curves/secp256k1", to: "https://ga.jspm.io/npm:@noble/curves@1.1.0/esm/secp256k1.js"
pin "@noble/hashes/_assert", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/_assert.js"
pin "@noble/hashes/crypto", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/crypto.js"
pin "@noble/hashes/hmac", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/hmac.js"
pin "@noble/hashes/pbkdf2", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/pbkdf2.js"
pin "@noble/hashes/scrypt", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/scrypt.js"
pin "@noble/hashes/sha256", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/sha256.js"
pin "@noble/hashes/sha3", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/sha3.js"
pin "@noble/hashes/sha512", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/sha512.js"
pin "@noble/hashes/utils", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.1/esm/utils.js"
pin "abitype", to: "https://ga.jspm.io/npm:abitype@0.7.1/dist/index.mjs"
pin "crc-32", to: "https://ga.jspm.io/npm:crc-32@1.2.2/crc32.js"
pin "cross-fetch", to: "https://ga.jspm.io/npm:cross-fetch@4.0.0/dist/browser-ponyfill.js"
pin "ethereum-cryptography/", to: "https://ga.jspm.io/npm:ethereum-cryptography@2.1.2/esm/"
pin "events", to: "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/browser/events.js"
pin "isomorphic-ws", to: "https://ga.jspm.io/npm:isomorphic-ws@5.0.0/browser.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.0.1/nodelibs/browser/process-production.js"
pin "setimmediate", to: "https://ga.jspm.io/npm:setimmediate@1.0.5/setImmediate.js"
pin "web3-core", to: "https://ga.jspm.io/npm:web3-core@4.3.0/lib/esm/index.js"
pin "web3-errors", to: "https://ga.jspm.io/npm:web3-errors@1.1.3/lib/esm/index.js"
pin "web3-eth", to: "https://ga.jspm.io/npm:web3-eth@4.3.0/lib/esm/index.js"
pin "web3-eth-abi", to: "https://ga.jspm.io/npm:web3-eth-abi@4.1.3/lib/esm/index.js"
pin "web3-eth-accounts", to: "https://ga.jspm.io/npm:web3-eth-accounts@4.1.0/lib/esm/index.js"
pin "web3-eth-contract", to: "https://ga.jspm.io/npm:web3-eth-contract@4.1.1/lib/esm/index.js"
pin "web3-eth-ens", to: "https://ga.jspm.io/npm:web3-eth-ens@4.0.7/lib/esm/index.js"
pin "web3-eth-iban", to: "https://ga.jspm.io/npm:web3-eth-iban@4.0.7/lib/esm/index.js"
pin "web3-eth-personal", to: "https://ga.jspm.io/npm:web3-eth-personal@4.0.7/lib/esm/index.js"
pin "web3-net", to: "https://ga.jspm.io/npm:web3-net@4.0.7/lib/esm/index.js"
pin "web3-providers-http", to: "https://ga.jspm.io/npm:web3-providers-http@4.1.0/lib/esm/index.js"
pin "web3-providers-ws", to: "https://ga.jspm.io/npm:web3-providers-ws@4.0.7/lib/esm/index.js"
pin "web3-rpc-methods", to: "https://ga.jspm.io/npm:web3-rpc-methods@1.1.3/lib/esm/index.js"
pin "web3-types", to: "https://ga.jspm.io/npm:web3-types@1.3.0/lib/esm/index.js"
pin "web3-utils", to: "https://ga.jspm.io/npm:web3-utils@4.0.7/lib/esm/index.js"
pin "web3-validator", to: "https://ga.jspm.io/npm:web3-validator@2.0.3/lib/esm/index.js"
pin "zod", to: "https://ga.jspm.io/npm:zod@3.22.4/lib/index.mjs"
